openapi: 3.0.0
info:
  title: AI Proxy API
  version: 1.0.0
paths:
  /api_chat.php:
    post:
      summary: Chat with AI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  One_Key:
                    type: string
                  role:
                    type: string
                  content:
                    type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  data:
                    type: object
                  message:
                    type: string
